Repository Extendy/SmartyURL, pull requests merged in 2023-10, with the labels that each got.

#34 working on new URL UI
  app/Config/Filters.php
  app/Config/Routes.php
  app/Config/Services.php
  app/Config/Smarty.php
  app/Config/Smartyurl.php
  app/Controllers/Assist.php
  app/Controllers/Tests.php
  app/Controllers/Url.php
  app/Filters/SmartyglobalFilter.php
  app/Filters/Webratelimit.php
  app/Helpers/smarty_helper.php
  app/Language/ar/Common.php
  app/Language/ar/Url.php
  app/Language/en/Common.php
  app/Language/en/Url.php
  app/Models/BaseModel.php
  app/Models/UrlTagsModel.php
  app/Views/basic/layout.php
  app/Views/basic/url/new.php
  composer.json
  composer.lock
  env
  public/static/css/select2-bootstrap.css
  public/static/css/urltags.css
  public/static/js/url/newurl.js
  public/static/js/url/newurl.min.js
  src/UrlTags.php
  src/WorldCountries.php
Labels: enhancement, coredev

#40 updating Add New URL UI
  .gitignore
  app/Config/Routes.php
  app/Config/Security.php
  app/Config/Smartyurl.php
  app/Controllers/Assist.php
  app/Controllers/Go.php
  app/Controllers/Url.php
  app/Views/basic/layout.php
  app/Views/basic/url/new.php
  app/Views/basic/url/segments/url_conditions.php
  composer.lock
Labels: coredev

#47 add the ability to modify URL.
  app/Config/Routes.php
  app/Controllers/Url.php
  app/Filters/Localization.php
  app/Language/ar/Url.php
  app/Language/en/Url.php
  app/Models/UrlTagsDataModel.php
  app/Models/UrlTagsModel.php
  app/Views/basic/dashboard.php
  app/Views/basic/url/new.php
  app/Views/basic/url/segments/url_conditions.php
  composer.lock
  env
  src/SmartyUrl.php
  src/UrlTags.php
Labels: coredev

#49 Change of devicecond handling
  app/Controllers/Go.php
  app/Controllers/Url.php
  app/Views/basic/url/segments/url_conditions.php
  blah
  src/SmartyUrl.php
  src/SmartyUrlDevice.php
  src/UrlConditions.php
Labels: enhancement, coredev

#52 Edit URL proccess
  .gitignore
  app/Config/AuthGroups.php
  app/Controllers/Url.php
  app/Language/ar/Url.php
  app/Language/en/Url.php
  app/Models/UrlModel.php
  app/Models/UrlTagsDataModel.php
  app/Views/basic/url/new.php
  blah
  composer.lock
  src/SmartyUrl.php
  src/UrlConditions.php
  src/UrlIdentifier.php
Labels: coredev

#53 set correct MIME type for javascript files
  app/Controllers/Assist.php
Labels: bug, coredev

#60 List Urls
  .gitignore
  app/Config/Auth.php
  app/Config/AuthToken.php
  app/Config/Autoload.php
  app/Config/Routes.php
  app/Config/Smartyurl.php
  app/Controllers/Assist.php
  app/Controllers/BaseController.php
  app/Controllers/Url.php
  app/Language/ar/Url.php
  app/Language/en/Url.php
  app/Views/basic/layout.php
  app/Views/basic/url/list.php
  blah
  composer.lock
  src/SmartyUrl.php
Labels: coredev

#63 feat: Complete ListURLs Layout with Correct View and Data
  app/Config/Routes.php
  app/Config/Smartyurl.php
  app/Controllers/Assist.php
  app/Controllers/Go.php
  app/Controllers/Url.php
  app/Filters/Localization.php
  app/Helpers/smarty_helper.php
  app/Language/ar/Url.php
  app/Language/en/Url.php
  app/Models/UrlModel.php
  app/Models/UrlTagsDataModel.php
  app/Views/basic/layout.php
  app/Views/basic/url/list.php
  public/static/css/smarty.rtl.css
  src/UrlTags.php
Labels: coredev

#64 docs: adding ip2location notice
  README.md
  _docs/ip2location.md
Labels: documentation
